### ISSUE TITLE
Lazy load the document

### ISSUE THREAD

**Issue by danielepolencic** [evnbr/regionize#3] opened 2020-12-05 07:31 UTC
Context: I'm here because I wanted to use Bindery.js.

We currently have a snippet of code that does this:

```tsx
import Bindery from 'bindery'

const HTML = <script dangerouslySetInnerHTML={{__html: `(${useBindery.toString()})()`}}>
function useBindery() {
  Bindery.makeBook({...})
}
```

In our case, the HTML is rendered server-side and shipped to the browser for execution.
The script fails with the current error:

```
ReferenceError: document is not defined
    at Object.<anonymous> (node_modules/regionize/dist/regionize.cjs.js:109:24)
    at Module._compile (internal/modules/cjs/loader.js:1200:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1220:10)
    at Module.load (internal/modules/cjs/loader.js:1049:32)
    at Function.Module._load (internal/modules/cjs/loader.js:937:14)
    at Module.require (internal/modules/cjs/loader.js:1089:19)
    at require (internal/modules/cjs/helpers.js:73:18)
    at Object.<anonymous> (node_modules/bindery/dist/bindery.cjs.js:25:17)
    at Module._compile (internal/modules/cjs/loader.js:1200:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1220:10)
```

Upon further inspection, I noticed that regionize expects the `document` to be immediately available:

![image](https://user-images.githubusercontent.com/1130499/101236784-cfc81c00-370e-11eb-99a0-28aa427780e2.png)

Unfortunately, `document` is not defined in Node.js (where we run the code).
I was wondering if you'd be open to a PR to fix that.
The change is: all the functions that use the `document` do so lazily.

**Comment by evnbr** [comment] 2020-12-06 06:30
Hi @danielepolencic — just trying to understand what's going on here. Bindery of course will not do anything when imported server-side, so I'm not sure what the intended behavior importing it in your code snippet would be?

Maybe you have same snippet of code, perhaps a React component, that runs server and client side, and so you'd rather bindery just fail to load silently when imported serverside?

**Comment by danielepolencic** [comment] 2020-12-06 07:09
> Maybe you have same snippet of code, perhaps a React component, that runs server and client side, and so you'd rather bindery just fail to load silently when imported serverside?

This. Correct.

**Comment by evnbr** [comment] 2020-12-08 19:34
Got it. Yes, no idea why i decided to write

`const createTextNode = document.createTextNode.bind(document);
`

vs something like

`const createTextNode = (text) => document.createTextNode(text);
`

... happy to accept a PR to that effect, but otherwise will try and push something out as an npm release later this week.

**Comment by evnbr** [comment] 2020-12-11 05:20
thanks for the PR— merged and bumped bindery versions. let me know if your scenario works now

**Closed as completed** 2020-12-17 01:08 UTC
